#version: "3.9"

services:

  rsyslog:
    image: rsyslog/syslog_appliance_alpine:latest
    container_name: rsyslog
    volumes:
      - ./config/rsyslog:/etc/rsyslog.d/:ro
      - ./logs:/var/log:rw
    restart: unless-stopped



  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_NICE
    volumes:
      - ./config/suricata/suricata.yaml:/etc/suricata/suricata.yaml:rw
      - ./logs/suricata:/var/log/suricata:rw
    environment:
      - RSYSLOG_SERVER=localhost
      - INTERFACE=${INTERFACE}
      - SURICATA_UPDATE_RULES=0
    command: [
      "-c", "/etc/suricata/suricata.yaml",
      "-i", "${INTERFACE}",
    ]
    restart: unless-stopped

  monparefeu:
    image: haythembj/parefeu:latest
    container_name: parefeu
    userns_mode: "host"
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./logs/monprojet.log:/var/log/monprojet.log:rw
      - ./logs/suricata:/var/log/suricata:rw
    depends_on:
      - rsyslog
      - suricata
    environment:
      - RSYSLOG_SERVER=localhost
    restart: unless-stopped
