version: "3.9"
services:
  monparefeu:
    image: haythembj/parefeu:latest
    network_mode: "host"
    container_name: parefeu
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    devices:
      - "/dev/net/tun:/dev/net/tun:rwm"
    volumes:
      - ./config/nftables.conf:/etc/nftables.conf
      - ./business.log:/app/business.log
      - ./config/templates/suricata.yaml:/etc/suricata/suricata.yaml
      - ./config/10-monprojet.conf:/etc/rsyslog.d/10-monprojet.conf
    environment:
      - SURICATA_INTERFACE=${INTERFACE}
    env_file:
      - .env
    restart: unless-stopped
